### ISSUE TITLE
Bulk visits upsert job in Salesforce not returning results

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/miraclefeet-india#11]
## Background, context, and business value
Miraclefeet India (MFI) is using a custom mobile application "CAST" to collect patient case data, which the MF Global team would like to integrate with its global Salesforce system. MFI developed a custom webservice that will daily publish a payload of new Clinic, Patient, and Visit data to the designated OpenFn inbox. This payload may contain thousands of JSON lines and individual records. To process this bulk dataset, when a new Message is received, OpenFn handleBulk.js (see job 1) will split the payload into separate Clinic, Patient, and Visit records, and post these data back to the OpenFn inbox. This will then trigger jobs 2a-2d (see here - add-visits.js, etc.) to run and map these records to Salesforce.

## The issue
We are seeing green checks in OpenFn when the jobs run, but when I check the run logs ([see example](https://www.openfn.org/projects/1778/runs/9978041)) for `add-visits.js` I don't see the results of the batch job returned and logs stop after `Executing batch...`. 
I don't think the bulk data load job is successfully being scheduled in Salesforce, because when I log into the SF sandbox and check out the Bulk Data Load Job logs ([go here](https://castapp--mfindia.lightning.force.com/lightning/setup/AsyncApiJobStatus/home)), I see jobs scheduled for Patients and Clinics, but none for Visits.

## state.json
Use [this message](https://www.openfn.org/projects/1778/messages/9563583) as your "data" in state. Note that this contains sensitive beneficiary info, so do NOT upload as sample data to Github.
```
{
  "configuration": {
      "loginUrl": "https://castapp--mfindia.lightning.force.com/",
      "username": "aleksa@openfn.org.mfindia",
      "password": "See LP - MiracleFeet MF India Sandbox",
      "securityToken": "See LP"
    },
"data":{...}
}
```
### adaptor
`language-salesforce` - note we're using the `bulk(...)` helper function here

### expression.js
So far in my testing, this issue seems isolated to `add-visit.js`. 

### output.json
Visit records should successfully post to Salesforce _and_ I expect to see the batch results in the logs -  something like the below snippet or this successful [patients run](https://www.openfn.org/projects/1778/runs/9978011) that shows me the Salesforce Ids created. 

```
Creating batch for job.
Executing batch.
{
  '$': { xmlns: 'http://www.force.com/2009/06/asyncapi/dataload' },
  id: '7510r000002Ui8vAAC',
  jobId: '7500r0000025m1kAAA',
  state: 'Queued',
  createdDate: '2020-09-28T06:35:54.000Z',
  systemModstamp: '2020-09-28T06:35:54.000Z',
  numberRecordsProcessed: '0',
  numberRecordsFailed: '0',
  totalProcessingTime: '0',
  apiActiveProcessingTime: '0',
  apexProcessingTime: '0'
}
Result : [
  {
    "id": "0030r00000U5edMAAR",
    "success": true,
    "errors": []
  },
  {
    "id": "0030r00000U5edNAAR",
    "success": true,
    "errors": []
  },
  {
    "id": "0030r00000U5edOAAR",
    "success": true,
    "errors": []
  },
  {
    "id": "0030r00000U5edPAAR",
    "success": true,
    "errors": []
  }
]
Finished.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 I _thought_ we had come across a similar issue before, but I can't find any helpful notes or chats. Not sure if you have other ideas you can share with Mamadou on troubleshooting this one.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , this `add-visit.js` job is currently running with a credential that's unrelated to Lwala! (It's pointed at an OpenFn demo Salesforce instance.) Three very quick things:

(1) Are the other jobs working as expected? (Sounds like yes, from the issue, but want to confirm.)
(2) Can we switch that credential now and test?
(3) Can we run these jobs multiple times on production without duplicating data?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 this is **miraclefeet-india**. we're all hooked up to sandbox, so feel free to run on prod as needed. Above I linked to this message that you can run on prod as many times as needed to reproduce: https://www.openfn.org/projects/1778/messages/9563642

**Comment by lakhassane** [comment]
@aleksa-krolls is it the right message payload? What you posted seem to be related to `HandleBulk.js` and not `add-visits.js`.

How about this one (taken from the run logs you posted): https://www.openfn.org/projects/1778/messages/9588815

**Comment by taylordowns2000** [comment]
@lakhassane , we discussed this already on our call (see my comment 40 min ago) and i've implemented the change, selecting a different credential.

 @aleksa-krolls , we're now having a failure related to a field that's missing: https://www.openfn.org/projects/1778/runs/9996368 - `Error: InvalidBatch : Field name not found : CommCare_Case_ID__c`. Please see when you get a chance.
