### ISSUE TITLE
Add transformations to `add-visits.js`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/miraclefeet-india#12]
## Background
See issue #9 --> this request is for MiracleFeet _India_!

## Request
The following 4 fields cause this job to fail because we need to transform the values provided in state before uploading to Salesforce. [See this sheet](https://docs.google.com/spreadsheets/d/1YNsJzztJywhnsmRjKcsNXCiL4_ANI7jPfQkU8ATKVvg/edit#gid=0) for instructions for transforming the choice values provided in state to Salesforce-compatible formats. 
https://github.com/OpenFn/miraclefeet-india/blob/7873aeb89bb6013ebcb9af4b5cd3a4f8118cdd2c/add-visits.js#L39-L43
Once these transformations have been added, you can remove the current `delete` statements in L39-43 to test. 

## state
See LP for `MiracleFeet MF India Sandbox`. 
Use `sampleVisits.json` for state with values to transform & test.  

## adaptor
`language-salesforce`

## expression
`add-visits.js`

## output
For this `sampleVisits.json`, I expect the following outputs: 
1. `"Bracing_Stage__c": "All day and night"` --> `'bracing_all_day'`
2. `"Relapse_Feet_Affected__c": "3"` --> `'Both'`
3. `"Relapse_Type_Right__c": "2,4"` --> `'Dynamic Supination; Adductus'`
4. `"Relapse_Type_Leftt__c": "1"` --> `'Cavus'`

**Comment by aleksa-krolls** [comment]
@taylordowns2000 wondering if you/Chaiwa would have time today to help me out with this quick one? (Mamadou has a lot on his plate.)

## Issue
Patients _and_Visits `Date_of_Tetonomy__c` sometimes come in the wrong format `DD-MM-YYYY`(e.g., `29-01-2020`) instead of `YYYY-MM-DD`. Uploads therefore fail in Salesforce. 

## Request
Can we please add a rule to (1) check if the date is in the format `YYYY-MM-DD`...
if not, then (2) convert `DD-MM-YYYY` to `YYYY-MM-DD` before uploading Visits. 

## state
See LP for `MiracleFeet Salesforce Production`
Patients: https://www.openfn.org/projects/pde3z9/messages/mbpbr8dp
Visits: https://www.openfn.org/projects/pde3z9/messages/m8qna8jj

## expressions
`add-visits.js`
`add-patients.js`

## To test
To test and for state, **re-run these failures on Prod:** 
Patients: https://www.openfn.org/projects/pde3z9/runs/r3xgx7yk
Visits: https://www.openfn.org/projects/pde3z9/runs/rbgegx4b

**Comment by taylordowns2000** [comment]
All good @aleksa-krolls . Please ask @hnyende directly for additional changes if needed!

- https://www.openfn.org/projects/pde3z9/runs/rwaeda9n
- https://www.openfn.org/projects/pde3z9/runs/rmkw4kg9
