### ISSUE TITLE
Help with testing - count records to be created

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/miraclefeet-india#14]
## Request
For [this Message](https://www.openfn.org/projects/1778/messages/9788300) can you please let me know how many `Patient` and `Visit` records I can expect to be created? (So count the # of Patients within the `Patient: [...]` array.)

Would it be possible to provide me a quick script I can run locally against different versions of `state` to verify our testing results? Thanks!

**Comment by lakhassane** [comment]
For this message @aleksa-krolls we have:
`52  Patient records created.`
`410  Visit records created.`
