### ISSUE TITLE
Map `MiracleFeet_Bar_Size__c` values to Salesforce options

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/miraclefeet-india#15]
## Request
Convert India-provided bar sizes to the list of available Salesforce options. If `MiracleFeet_Bar_Size__c` has a string value that _contains_ `'150 mm'`, `'180 mm'` or `'220 mm'` --> return the appropriate size. 
```
'150 mm': 'Extra Small', 
'180 mm': 'Small', 
'220 mm': 'Large' 
```
Handle for scenarios where `MiracleFeet_Bar_Size__c` may not be defined or set to a `""` or ` "-"` value. 

## state
See LP for `MF India Sandbox`. 

Use `sample_data/visit.json` for state. 

## adaptor
`language-salesforce

## expression
https://github.com/OpenFn/miraclefeet-india/blob/dfd85f1aec54c367ed6f5fbb04ffa69f443a63f4/add-visits.js#L1-L94

## output
The `visit.json` state has the bar size `180 mm` and should return the size `'Small'` when we upload to Salesforce.

**Comment by chaiwa-berian** [comment]
Hi @aleksa-krolls I have opened a pull request for this issue but I need your input before finalising for your testing:

1. Should we search the string using regex to match a group of `digits` followed by a `space`, ` mm`at either at the start or end of the string? (Examples of possible matches would be `120 mm`, `120mm`, `120 mm some additional text`, `some text 120 mm`.) Or should we match only on last 6 digits of the string, no matter what? (**Possible matches:** `120 mm`, `some text 120 mm` ; **Non-Matches:** `120mm`, `80 mm`, `120 mm some text`)

2. What should we do when there is no match? (Right now we return `-` which marks the field for deletion by `clean()` function.)

**Comment by aleksa-krolls** [comment]
Thanks @chaiwa-berian 
1. At minimum, we need to support the second option where the value (e.g., `180 mm`) will be at the end of the string. If you already have the first option in place, that will work too. 
2. Cool if setting to `-` works - because I would like it to be removed from the payload sent to Salesforce.

**Comment by aleksa-krolls** [comment]
@chaiwa-berian Testing passing and working great - thanks Chaiwa!
