### ISSUE TITLE
JSON Message too big, please help me chunk this & re-post to OpenFn Inbox

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/miraclefeet-india#19]
## Background, context, and business value
MF India team posted too large of a payload to OpenFn, causing OpenFn to throw a memory limit part way through processing. See Message here: https://www.openfn.org/projects/pde3z9/messages/mj4p7jvr

Can you please help me (1) split up the JSON Message into smaller payload sizes, and then (2) repost these smaller payloads to the OpenFn Inbox? 
https://www.openfn.org/projects/pde3z9/messages

Please note that every payload has a structure that looks like this multiple arrays. 
```
{
    "Clinic": [
        {
            "Active__c": true,
            "CAST_Location_ID__c": 29,
            "Country__c": "-",
            "CreatedById": null,
            "LastModifiedById": "PM_6006",
            "Name": "BJ Wadia Children's Hospital Mumbai",
            "OwnerId": "-",
            "Start_Date__c": "2018-09-01",
            "Zone__c": "27"
        }
    ],
    "LookupTable": [...],
    "Patient": [...],
    "Visit": [...],
    "VisitDeleted": [],
}
```
For the integration to work successfully, ensure...
1. All of these array are present in the payload (i.e., even if you're not including any Patient data in your chunked payload, please still include `"Patient":[],` in the payload
2. Include the full data for `Clinic` and `LookupTable` in the array. (These tell the job how to map related Patient and Visit data, so need to be in each payload)

Please do this all on Prod, but feel free to post from your local machine to the OpenFn inbox.

**Comment by aleksa-krolls** [comment]
@lakhassane Fyi, looks like these Message sizes are still too big :/ : https://www.openfn.org/projects/pde3z9/runs/rwa5k6nz

**Comment by aleksa-krolls** [comment]
@lakhassane this is priority after Moodle (if able to still proceed with that and not affect work)

**Comment by lakhassane** [comment]
@aleksa-krolls I made the job to split the state in multiple sampleData to feed `handleBulk.js`.
I just made a test and you can some runs for handleBulk in the Activity History.

I did not run the whole big state until the others jobs are activated and ready to go because it might be helluva runs in the inbox.

**Comment by aleksa-krolls** [comment]
@lakhassane I've realized that there are some more messages we need to split up as well (just as you did before, ensuring `LookupTable` was included in each payload): 
https://www.openfn.org/projects/pde3z9/messages/mrbmj4mm
https://www.openfn.org/projects/pde3z9/messages/mz7maj6g
https://www.openfn.org/projects/pde3z9/messages/mpqgnkmq
https://www.openfn.org/projects/pde3z9/messages/mdb5qe5v

Please... 1) split these into smaller messages, 2) post to the OpenFn inbox, and 3) this will trigger job `1. Handle Bulk CAST Data`. (I will turn off jobs 2-4 so that you can more easily monitor the inbox... thank you!)

**Comment by aleksa-krolls** [comment]
@taylordowns2000 See here for context on the MFI issue. 

See here for the MFI solution overview: https://github.com/OpenFn/miraclefeet-india#technical-overview

**Comment by aleksa-krolls** [comment]
@lakhassane per our conversation, please pause here until Taylor provides more info on the memory limits and message sizes.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 can @lakhassane go ahead and break up these massive payloads that India originally posted into smaller chunks that are `< 50,000 lines of JSON`? (If you look at the `Associated Runs` for these, you'll see that all the runs hit the memory limit error.)

I know you're re-factoring the `1. Handle Bulk CAST Data` job, but I'm wondering if this task can still be done? And should we turn off the job `1` until it has been re-factored to run again these smaller payloads?  

Thanks for the support. Want to make sure next steps are clear, so holler on Slack/Whatsapp, if helpful.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , @lakhassane , while i'd still do them one-at-a-time to make sure no _new_ issues arise, the remaining bulk payloads from MF india can be processed whenever you'd like. See a list of those remaining here: https://www.openfn.org/projects/pde3z9/messages?endDate=2021-03-23T17%3A17%3A40.287Z&jobStates=fail&triggerId=ty4m3a

Let's chat about the adjustments Stu made this AM, good stuff in there.

1. My commit last night, fixing memory but failing to wait for the result of all those promises: https://github.com/OpenFn/miraclefeet-india/commit/def6d44cd52697aa0820ed764cb341d4e311cc62
2. Stu's commit this AM, making us wait for the promises: https://github.com/OpenFn/miraclefeet-india/commit/ace62739ef78280aeb856988a78df88b267d4e00

**Comment by aleksa-krolls** [comment]
@taylordowns2000 I am still unable to process this big guy... it doesn't even look like the job will start running. 
https://www.openfn.org/projects/pde3z9/messages/mpqgnkmq
```
This run could not be started: %Oban.CrashError{message: "** (throw) \"Killing run before execution; artifacts @\\\"13.371\\\"MB\"", reason: "Killing run before execution; artifacts @\"13.371\"MB"}
```
Should I ask @lakhassane to break it into small payloads?

**Comment by aleksa-krolls** [comment]
Also @taylordowns2000 not sure what you did to the `1. Handle Bulk CAST Data` job, but it's not posting any data back to the inbox... do we need to comment back in L111-118? 
See my successful bulk run here: https://www.openfn.org/projects/pde3z9/runs/rx8g4r5r
Now check out the inbox... it's full of messages that look like this (it looks like there is a count, but no actual data). 
https://www.openfn.org/projects/pde3z9/messages
```
{
  "__query_params": {},
  "visits": "100"
}
```

**Comment by taylordowns2000** [comment]
two remaining: https://www.openfn.org/projects/pde3z9/messages?endDate=2021-03-23T17%3A17%3A40.287Z&jobStates=fail&triggerId=ty4m3a

**Comment by aleksa-krolls** [comment]
Y'all are stars. Thanks for getting this one over the line @taylordowns2000 @lakhassane
