### ISSUE TITLE
Update Handle Bulk logs & count records

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/miraclefeet-india#20]
MF India team is reporting that some of the data they uploaded to OpenFn is missing from Salesforce. I need your help auditing the payloads sent so that we can verify this. (See issue #19 for the history of the trouble we had processing the very large payloads they sent over.)

## Request
1. Please update the logs for the `HandleBulk.js` job to log the counts for # of Clinics, Patients, and Visits for every bulk payload received. 
2. Would it be possible to create a new `auditRecordCount.js` job in prod that I can run on-demand against any JSON payload to see these total # of records? Can you please set this up so that I can check the counts for all bulk payloads they have sent historically? (The job shouldn't do anything else... so need to process any data.)

## To Test
1. For `1` - please run `HandleBulk.js` against this Message _on prod_: https://www.openfn.org/projects/pde3z9/messages/mk57rkqm
2. For `2` - please test against these messages to report back the counts. 
a. https://www.openfn.org/projects/pde3z9/messages/mn5kngbz
b. https://www.openfn.org/projects/pde3z9/messages/mrbmj4mm
c. https://www.openfn.org/projects/pde3z9/messages/mdb5qe5v

**Comment by lakhassane** [comment]
I left some logs on `handleBulk.js`but can't run now.

I also made the `auditRecordCount.js` job that you can run on any state to see the count of the different sets.

**Comment by aleksa-krolls** [comment]
@lakhassane thanks for this :)
