### ISSUE TITLE
MF auditing - record count by Clinic

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/miraclefeet-india#21]
## Background
See issues #19 and #20 for a background on the issues here where MF India originally sent too large of payloads to OpenFn that we then had to chunk and re-send to Salesforce. 

MF India is reporting that they sent different record counts than what I see have been uploaded to Salesforce. See summary of record counts here: https://docs.google.com/spreadsheets/d/178dWyaIw53lgDeEAO_xtuPIuv_BPeJXwAL2FGhQFvtc/edit#gid=439017287

## Request
For 2 clinics, `BJ Wadia Children's Hospital Mumbai` and `Kandivali Hitwardhak Mandal Hospital`, I need to know the record counts in OpenFn so that we can determine if this is a MFI- or Salesforce-side issue. 

Currently the `auditRecordCount.js` job provides a total # of Clinic, Patient, and Visit records ([see example run](https://www.openfn.org/projects/pde3z9/runs/raawdprx))... but this doesn't tell me how many # of Patients and Visits _per clinic_. 

Note that 1 OpenFn payload might have more than 1 Clinic... so can you please group the `Patient` and `Visit` record counts by the JSON key `CreatedById` so that we can see how many patients and visits for these 2 clinics: 
1. `BJ Wadia Children's Hospital Mumbai` -> `CreatedById: MH01` - here are the 2 payloads to check: 
https://www.openfn.org/projects/pde3z9/messages?endDate=2021-03-02T08%3A25%3A00.000Z&startDate=2021-02-16T07%3A25%3A43.195Z&triggerId=t9kwqq
2. `Kandivali Hitwardhak Mandal Hospital`-> `CreatedById: MH03` - here are the 2 payloads to check: 
https://www.openfn.org/projects/pde3z9/messages?endDate=2021-03-02T08%3A26%3A00.000Z&startDate=2021-02-16T07%3A26%3A11.482Z&triggerId=tygmad

Amazing if you can help me fill in this sheet so I can report back to the India team: https://docs.google.com/spreadsheets/d/178dWyaIw53lgDeEAO_xtuPIuv_BPeJXwAL2FGhQFvtc/edit#gid=439017287
And if we're seeing discrepancies between what the India team is reporting and what we see in OpenFn then @taylordowns2000 this is where I may need your help on the call with the India team tomorrow afternoon to discuss what might have went wrong when they posted those very large datasets to OpenFn. 

## expression
`auditRecordCount.js`

**Comment by aleksa-krolls** [comment]
@lakhassane the BJ Wadia messages are too big to run this on prod. Can you please run these 2 locally and share screenshots of the stats counts. Thanks. 
https://www.openfn.org/projects/pde3z9/messages?endDate=2021-03-02T08%3A26%3A00.000Z&startDate=2021-02-16T07%3A26%3A11.482Z&triggerId=t9kwqq

**Comment by aleksa-krolls** [comment]
@lakhassane See my comment above. And here is a third message I am unable to run the audit for because of this `TypeError`: https://www.openfn.org/projects/pde3z9/runs/renennjb

**Comment by aleksa-krolls** [comment]
@lakhassane thanks for the help so far... now I narrowed the data discrepancy issue to 1 clinic (BJ Wardia) - see here: https://docs.google.com/spreadsheets/d/178dWyaIw53lgDeEAO_xtuPIuv_BPeJXwAL2FGhQFvtc/edit#gid=439017287

I see 2 Messages that have this clinic's data... across _both_ messages, I want to know the unique `patient` record count and unique `visit` count. Can you please help me to...
1. Combine the 2 Messages into 1 payload
https://www.openfn.org/projects/pde3z9/messages/mpqgnkmq
https://www.openfn.org/projects/pde3z9/messages/mrbmj4mm
2. Provide count of unique `patients` (uid: `CommCare_Case_ID__c`) by Clinic (uid: `CreatedById`)
3. Provide count of unique `visits` (uid: `Visit_ID__c`) by Clinic (uid: `CreatedById`)

I'm to understand if the Messages provide duplicate data to determine the total record counts for this Clinic across all payloads sent to OpenFn. Thanks!

**Comment by aleksa-krolls** [comment]
@taylordowns2000 See related Slack thread for how Mamadou chunked this and we tried to run... but kept hitting `ENOTFOUND` issues when posting to OpenFn Inbox: https://openfn.slack.com/archives/G2LJCFFDW/p1621336129007100?thread_ts=1621326155.003500&cid=G2LJCFFDW
I don’t think we correctly chunked this large JSON payload and got everything back into the Inbox… because the record counts check out, but SF doesn’t reflect everything. Can I ask you to please (1) chunk this message to break into smaller payload sizes, and then (2) re-post the smaller payloads to the Inbox? Goal is to resync this batch of data: 
https://www.openfn.org/projects/pde3z9/messages/mrbmj4mm

**Comment by taylordowns2000** [comment]
https://openfn.slack.com/archives/G2LJCFFDW/p1621343364015000
