### ISSUE TITLE
Handle multi-select fields when translating values using `LookupTable`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/miraclefeet-india#22]
## Background 
See issue #9 for how we use the `LookupTable` provided in state to translate coded values to string picklist values. 

## Request
For these fields where we receive multiple values as 1 string - please parse the string provided in state into multiple string values, translate to Salesforce picklist values using the `LookupTable`, and then return as a semicolon-separated string in order to successfully upload to Salesforce. 

**Current Input - Example state:** 
```
"Relapse_Type_Left_Foot__c": "1,2,3,4,5,6",
"Relapse_Type_Right_Foot__c": "1,2,3,4",
```

LookupTable tells us we should translate these values as follows below. 
```
{
      "AppFieldName": "Relapse_Type_Left__c",
      "Description": "Cavus",
      "LookupCode": 1
    },
    {
      "AppFieldName": "Relapse_Type_Left__c",
      "Description": "Adductus",
      "LookupCode": 2
    },
    {
      "AppFieldName": "Relapse_Type_Left__c",
      "Description": "Varus",
      "LookupCode": 3
    },
    {
      "AppFieldName": "Relapse_Type_Left__c",
      "Description": "Equinus",
      "LookupCode": 4
    },
    {
      "AppFieldName": "Relapse_Type_Left__c",
      "Description": "Rigid Cave",
      "LookupCode": 5
    },
    {
      "AppFieldName": "Relapse_Type_Left__c",
      "Description": "Dynamic Supination",
      "LookupCode": 6
    },
```
Currently because we read `"1,2,3,4,5,6"` as one value (instead of 6 separate values), we don't find this in the LookupTable and instead output `"Relapse_Type_Left_Foot__c": "1,2,3,4,5,6"`. This throws this error (https://www.openfn.org/projects/pde3z9/runs/rbg7pz4p) when we upload to Salesforce. 

**Instead, please output: **
```
"Relapse_Type_Left_Foot__c": "Cavus;Adductus;Varus;Equinus;Rigid Cave;Dynamic Supination",
"Relapse_Type_Right_Foot__c": "Cavus;Adductus;Varus;Equinus",
```

## state
**To test, use this Message:** https://www.openfn.org/projects/pde3z9/messages/m58raj3a
This will trigger the `handleBulk.js` job that then parses this into separate Patient messages... which currently are failing to upload - see run here: https://www.openfn.org/projects/pde3z9/runs/rbg7pz4p

See LP for `MiracleFeet Salesforce Production`

## expression
https://github.com/OpenFn/miraclefeet-india/blob/master/handleBulk.js
that triggers...
https://github.com/OpenFn/miraclefeet-india/blob/master/add-patients.js

## output
Semicolon separated string. 
Example Input: 
```
"Relapse_Type_Left_Foot__c": "1,2,4",
```

Desired output: 
```
"Relapse_Type_Left_Foot__c": "Cavus;Adductus;Equinus",
```

**Comment by lakhassane** [comment]
@aleksa-krolls you should be good to go

**Comment by aleksa-krolls** [comment]
@lakhassane It looks like the value outputted is comma-separated rather than semicolon `;` separated. See the error in this run: https://www.openfn.org/projects/pde3z9/runs/r6g7k55z

**Comment by aleksa-krolls** [comment]
@lakhassane failing with `TypeError`: https://www.openfn.org/projects/pde3z9/runs/ryapajrj

Please re-run on prod when fixed to confirm!

**Comment by lakhassane** [comment]
@aleksa-krolls find the ongoing (proly done now) run here with the POST made: https://www.openfn.org/projects/pde3z9/runs/rk5r5may

**Comment by aleksa-krolls** [comment]
@lakhassane I'm seeing the output `Relapse_Type_Left_Foot__c: 'Cavus;2;3;4;5;6',` in this run where only 1 of the values are translated. We need every integer (`1`, `2`, `3`) to be translated via the `LookupTable` and then joined by `;`. 
https://www.openfn.org/projects/pde3z9/runs/rpd9d3w7

Can you please prioritize getting this done today? Let me know how I can help.
