### ISSUE TITLE
Audit record count - dynamically group by clinic code

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/miraclefeet-india#23]
## Background
See related issue #21. I need a report of total unique `Patient` and `Visit` counts by clinic... but currently we're hardcoding and looking only for specific clinics (`MH01`, `MH03`), however these clinic codes could change with each upload. Therefore the current logs aren't very helpful - see run: https://www.openfn.org/projects/pde3z9/runs/r89yn4kg

## Request
Find unique `Patient` and `Visit` record counts, but group by the `CAST_Location_ID__c` to dynamically show this count by clinic code. 

<img width="344" alt="Screen Shot 2021-07-09 at 11 24 38 AM" src="https://user-images.githubusercontent.com/16758106/125048254-66472c00-e0a8-11eb-85ef-53f7e6946fa3.png">

## expression
https://github.com/OpenFn/miraclefeet-india/blob/e65599334a127c664e06d3f873478a218d61fc24/auditRecordCount.js#L55-L65

**Comment by aleksa-krolls** [comment]
@lakhassane What's the status on this one? Complete or still work to do? (I will prioritize in the backlog, if needed... but today it's lower priority than some of these other ones.)

**Comment by lakhassane** [comment]
@aleksa-krolls this is ready for testing.
