### ISSUE TITLE
Update source value mapping for Visit External Id

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/miraclefeet-india#4]
https://github.com/OpenFn/miraclefeet-india/blob/35ee1d7d8931c7855319539f28e2d3ef5d7cc96d/add-clinic-patient-visit.js#L65

In Salesforce, the Visit external Id field we'll use to upsert records is `gciclubfootommcare_case_id__c` (destination). 

However, from [state ](https://github.com/OpenFn/miraclefeet-india/blob/master/sample_data/payload_new.json)we should use `Visit_ID__c` as the source value for this field. 

So please add the below mapping and make sure this new value is used in the external Id upsert. (and excuse my pseudo code) 
`field('gciclubfootommcare_case_id__c', dataValue('Visit[x].Visit_ID__c'))`

**Comment by taylordowns2000** [comment]
@aleksa-krolls , i've implemented this and _removed_ `Visit_ID__c` from the sf-bound payload, since it looked like we did the same thing with case id above it:
```js
p.CommCare_Case_ID__c = p.CAST_Patient_ID__c; // set some new field based on some other field
delete p.CAST_Patient_ID__c; // delete that other field, i.e., don't send it to SF
```
