### ISSUE TITLE
Break bulk operations out into separate jobs? 

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/miraclefeet-india#5]
https://github.com/OpenFn/miraclefeet-india/blob/35ee1d7d8931c7855319539f28e2d3ef5d7cc96d/add-clinic-patient-visit.js#L47

For (1) better error handling/UX and to (2) ensure this job can process messages with thousands of lines of JSON, I'm thinking we should create 4 separate jobs from this one job: 

1. Upsert Clinics
2. Upsert Patients
3. Upsert Visits
4. Delete Visits (this is not yet implemented in this job - see specs in issue #6 )

**Can you please (1) break out into separate jobs and (2) test these jobs with the large message linked to below?** (I want to ensure we're not going to encounter issues w/ processing time.)

- For state, please use [this message](https://www.openfn.org/projects/1778/messages/8703919) to test. (I have not uploaded as sample data bc it contains actual client data.) 
- [This sample data](https://github.com/OpenFn/miraclefeet-india/blob/master/sample_data/payload_new.json) also provides subset of data to test with.

**Comment by taylordowns2000** [comment]
hey @aleksa-krolls , i've got the basic pattern going. the first "handle" job requires a raw json credential with a body of `{inboxUrl: "your-full-token-url"}`at least.

the next job (`add-clinics.js`) should have a filter trigger with a criteria value of `{clinics: []}`.

before going further with this, i'd like to see that it's working on the site. can you test it out and confirm that it does what you want?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Thanks for creating `add-visits.js` and `add-patients.js`. I will test with Hailey tomorrow and revert back with any issues.
