### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/miraclefeet-india#7]
https://github.com/OpenFn/miraclefeet-india/blob/2c05844d2f95f0854d83991e3a4c9b31da26060d/handleBulk.js#L6

[This run](https://www.openfn.org/projects/1778/runs/9141619) fails with error `TypeError: Cannot read property 'push' of undefined`. 

We ran [this same message](https://www.openfn.org/projects/1778/messages/8703919) offline with success, but I neglected to test `handleBulk.js` via the web app yesterday. Any ideas why it's not picking up the array?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Lmk if you can fit this in today, and keep me posted if I can help with testing!

**Comment by taylordowns2000** [comment]
Hey @aleksa-krolls , this looks OK now. I changed the adaptor to use HTTP (this isn't actually a salesforce job) and added that new `raw JSON` credential.

![image](https://user-images.githubusercontent.com/8732845/84912257-7b54b580-b076-11ea-88af-a53893ca76ea.png)

**Comment by aleksa-krolls** [comment]
@taylordowns2000 [face palm] of course, forgot that final step. thank you
