### ISSUE TITLE
SF bulk `delete` operation not working, LP updates needed? 

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/miraclefeet-india#8]
https://github.com/OpenFn/miraclefeet-india/blob/d46462f8efcfdfe3ae9f4f47f7a61334fadb85e6/delete-visits.js#L22-L28

[Here](https://www.openfn.org/projects/1778/runs/9170280) is a failed OpenFn run for `delete-visits.js` that fails with the error `Error: InvalidBatch : Records not found`. 

[See here](https://castapp--mfindia.lightning.force.com/lightning/setup/AsyncApiJobStatus/home) for the **Bulk Data Load Job** logs in the sandbox. It does not look like Salesforce receives the external `Id` from OpenFn.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , this looks good from my end: https://castapp--mfindia.lightning.force.com/lightning/setup/AsyncApiJobStatus/page?address=%2F7500r000000F7Y5

Can you check it out?
